---
- hosts: ec2
  remote_user: ubuntu
  sudo: True

  tasks:

    - name: Install packages with apt
      apt: pkg={{item}} update_cache=yes
      with_items:
        - python-pip 
        - git
        - python-dev
        - libffi-dev
        - libssl-dev
        - nginx
        - default-jdk

    - name: Install uwsgi
      pip: name=uwsgi

    - name: Pull easy-key-z source code
      git: repo=https://github.com/fuentesj/easy-key-z.git dest=/opt/easy-key-z

    - name: Install requirements.txt
      pip: requirements=/opt/easy-key-z/server/requirements.txt extra_args=--ignore-installed

    - name: Create directories for certificate components
      file: state=directory owner=ubuntu mode=0755 path=/opt/easy-key-z/server/{{item}}
      with_items:
        - private_keys
        - certificate_signing_requests
        - certificates

    - name: Install upstart script for uwsgi
      template: src=server/easy-key-z.conf dest=/etc/init/easy-key-z.conf

    - name: Create dir for easy-key-z within nginx sites-available dir
      file:
        state: directory 
        path: /etc/nginx/sites-available/easy-key-z

    - name: Create log directory
      file:
        state: directory
        path: /tmp/easy-key-z-log/
        owner: ubuntu
        group: www-data
        mode: 0775

    - name: Create log file
      file:
        state: touch
        path: /tmp/easy-key-z-log/server.log
        owner: ubuntu
        group: www-data
        mode: 0775

    - name: Install nginx config file 
      template: src=server/easy-key-z-nginx-config dest=/etc/nginx/sites-available

    - name: Add symlink betwen sites-available and sites-enabled
      file:
        src: /etc/nginx/sites-available/easy-key-z-nginx-config
        dest: /etc/nginx/sites-enabled/easy-key-z
        state: link
        force: yes

    - name: Restart uwsgi
      service: name=easy-key-z state=restarted 

    - name: Restart nginx
      service: name=nginx state=restarted
