---
- hosts: ec2
  remote_user: ubuntu
  sudo: True
  vars:
    wsgi_file: rest_api.py
    wsgi_callable: app

  tasks:

    - name: Install pip
      apt: pkg=python-pip update_cache=yes

    - name: Install git
      apt: pkg=git

    - name: Install python-dev
      apt: pkg=python-dev

    - name: Install libffi-dev
      apt: pkg=libffi-dev

    - name: Install libssl-dev
      apt: pkg=libssl-dev

    - name: Install nginx
      apt: pkg=nginx

    - name: Install virtualenv
      pip: name=virtualenv

    - name: Install uwsgi
      pip: name=uwsgi

    - name: Pull easy-key-z source code
      git: repo=https://github.com/fuentesj/easy-key-z.git dest=/opt/easy-key-z

    - name: Install requirements.txt
      pip: requirements=/opt/easy-key-z/server/requirements.txt extra_args=--ignore-installed

    - name: Install upstart script for uwsgi
      template: src=server/easy-key-z.conf dest=/etc/init/easy-key-z.conf

    - name: Create dir for easy-key-z within nginx sites-available dir
      file:
        state: directory 
        path: /etc/nginx/sites-available/easy-key-z

    - name: Install nginx config file 
      template: src=server/easy-key-z-nginx-config dest=/etc/nginx/sites-available

    - name: Change permissions on Unix socket file
      file:
        path: /opt/easy-key-z/server/easy-key-z.sock 
        mode: 0666

    - name: Restart uwsgi
      service: name=easy-key-z state=restarted

    - name: Add symlink betwen sites-available and sites-enabled
      file:
        src: /etc/nginx/sites-available/easy-key-z-nginx-config
        dest: /etc/nginx/sites-enabled/easy-key-z
        state: link
        force: yes

    - name: restart nginx
      service: name=nginx state=restarted
